/* Review Reply Agent — mock data */

const LOCATIONS = [
  { id: "ams", name: "Amsterdam Centrum", channels: "Google · Yelp · Tripadvisor", enabled: true },
  { id: "rot", name: "Rotterdam Markthal", channels: "Google · Yelp", enabled: true },
  { id: "utr", name: "Utrecht Domplein", channels: "Google · Tripadvisor", enabled: false },
];

const STATS = [
  { key: "sent", label: "Replies sent", value: "47", icon: "send", tone: "green",
    sub: "Across Google, Yelp and Tripadvisor" },
  { key: "time", label: "Time saved", value: "2h 44m", icon: "clock", tone: "warm",
    sub: "Based on 3.5 minutes per reply" },
  { key: "auto", label: "Handled automatically", value: "92", unit: "%", icon: "sparkle", tone: "blue",
    sub: "Only sensitive reviews need approval" },
  { key: "pending", label: "Pending approval", value: "3", icon: "inbox", tone: "amber",
    sub: "Low-rating replies waiting for review" },
];

// reviews needing attention (also seed the detail modal)
const ATTENTION = [
  {
    id: "mike", name: "Mike T.", rating: 1, loc: "Amsterdam Centrum", platform: "Yelp", ago: "2 days ago",
    text: "Terrible service. Waiter was rude and we waited 40 minutes for our mains to arrive.",
    status: "draft", statusLabel: "Draft ready", statusTone: "info",
    reason: "Negative review", reasonTone: "error", action: "Review reply",
    confidence: 0.62,
    reply: "Thank you for sharing your experience, Mike. I'm genuinely sorry the service fell short and that your mains took so long — that's not the standard we hold ourselves to. I've passed this to our floor manager. We'd love the chance to make it right; please reach out and your next visit is on us.",
  },
  {
    id: "emma", name: "Emma W.", rating: 3, loc: "Utrecht Domplein", platform: "Tripadvisor", ago: "4 days ago",
    text: "Great ambiance but the menu felt limited and a few dishes were a little underwhelming.",
    status: "approval", statusLabel: "Needs approval", statusTone: "warn",
    reason: "Mixed feedback", reasonTone: "warn", action: "Approve",
    confidence: 0.78,
    reply: "Thank you, Emma — we're so glad you enjoyed the ambiance. Your note on the menu is fair, and we're rotating in several new dishes this season. We'd love to welcome you back to try them.",
  },
  {
    id: "lisa-a", name: "Lisa K.", rating: 4, loc: "Rotterdam Markthal", platform: "Google", ago: "5 days ago",
    text: "Decent food, nothing special. Friendly staff though and a nice spot for a quick lunch.",
    status: "tone", statusLabel: "Check tone", statusTone: "warm",
    reason: "Low confidence", reasonTone: "neutral", action: "Edit",
    confidence: 0.54,
    reply: "Thanks for dining with us, Lisa, and for the kind words about our team. We'd love to make your next visit feel a little more special — come hungry and let us surprise you.",
  },
];

const ACTIVITY = [
  { type: "sent",  text: "Replied to <b>Sarah M.</b>'s 5-star Google review", time: "2 min ago" },
  { type: "draft", text: "Drafted a reply for <b>Mike T.</b>'s 1-star review", time: "18 min ago" },
  { type: "skip",  text: "Skipped a Tripadvisor review — flagged for human approval", time: "1h ago" },
  { type: "sync",  text: "Synced <b>12 new reviews</b> from Rotterdam Markthal", time: "1h ago" },
  { type: "tone",  text: "Applied your <b>Professional</b> tone preset", time: "Yesterday" },
  { type: "sent",  text: "Replied to <b>Tom V.</b>'s 5-star Google review", time: "Yesterday" },
];

const HISTORY = [
  { id: "h1", name: "Sarah M.", rating: 5, review: "Absolutely wonderful experience from start to finish.",
    reply: "Thank you so much, Sarah — we can't wait to welcome you back.",
    loc: "Amsterdam Centrum", platform: "Google", status: "auto", date: "09/06/2026", time: "14:32",
    confidence: 0.96 },
  { id: "h2", name: "Jan de V.", rating: 2, review: "Food was okay but the wait time was far too long.",
    reply: "Thank you for your feedback, Jan. We're sorry about the wait and are addressing it.",
    loc: "Rotterdam Markthal", platform: "Google", status: "auto", date: "08/06/2026", time: "19:08", isNew: true,
    confidence: 0.81 },
  { id: "h3", name: "Mike T.", rating: 1, review: "Terrible service. Waiter was rude and we waited far too long.",
    reply: "Thank you for sharing your experience. I'm genuinely sorry the service fell short…",
    loc: "Amsterdam Centrum", platform: "Yelp", status: "auto", date: "10/06/2026", time: "10:47", isNew: true,
    confidence: 0.62 },
  { id: "h4", name: "Lisa K.", rating: 4, review: "Decent food, nothing special. Friendly staff though.",
    reply: "Thank you for dining with us, Lisa. We'd love to make your next visit special.",
    loc: "Rotterdam Markthal", platform: "Google", status: "failed", date: "07/06/2026", time: "16:21", isNew: true,
    confidence: 0.74 },
  { id: "h5", name: "Emma W.", rating: 3, review: "Great ambiance but the menu felt limited.",
    reply: "—",
    loc: "Utrecht Domplein", platform: "Google", status: "auto", date: "06/06/2026", time: "12:05",
    confidence: null },
  { id: "h6", name: "Daan H.", rating: 5, review: "Best dinner we've had in Amsterdam this year.",
    reply: "What a lovely thing to read, Daan — thank you. See you again soon.",
    loc: "Amsterdam Centrum", platform: "Google", status: "auto", date: "06/06/2026", time: "20:18",
    confidence: 0.97 },
  { id: "h7", name: "Femke B.", rating: 4, review: "Lovely natural wines and a warm room. Slightly slow at the pass.",
    reply: "Thank you, Femke — so glad you enjoyed the wines. We're tightening up service times.",
    loc: "Rotterdam Markthal", platform: "Google", status: "auto", date: "05/06/2026", time: "18:54",
    confidence: 0.88 },
  { id: "h8", name: "Pieter K.", rating: 2, review: "Booking was a mess and our table wasn't ready.",
    reply: "Thank you for your feedback, Pieter. We're sorry about the booking mix-up…",
    loc: "Utrecht Domplein", platform: "Google", status: "auto", date: "05/06/2026", time: "09:26",
    confidence: 0.66 },
  { id: "h9", name: "Noor V.", rating: 5, review: "The tasting menu was a highlight of our trip.",
    reply: "Thank you, Noor — that means the world to the kitchen. Until next time.",
    loc: "Amsterdam Centrum", platform: "Tripadvisor", status: "auto", date: "04/06/2026", time: "21:11",
    confidence: 0.95 },
  { id: "h10", name: "Marlies S.", rating: 4, review: "We came in with a group of six after a long conference day and the team handled the whole evening beautifully. The table was ready, the wine advice felt personal, and the shared starters arrived at a relaxed pace. The only thing that could be improved is that our mains came out a little unevenly, so two people had to wait while the rest of us already had our food.",
    reply: "Thank you, Marlies. It is lovely to read that the evening felt easy and well looked after, especially after a long day. We are glad the wine advice and shared starters landed well. We also appreciate your note about the timing of the mains and will take that back to the team so everyone at the table can enjoy the same rhythm next time.",
    loc: "Amsterdam Centrum", platform: "Google", status: "auto", date: "03/06/2026", time: "15:39",
    confidence: 0.91 },
  { id: "h11", name: "Olivier R.", rating: 2, review: "The room looked great and our server was kind, but the experience did not match what we expected for the price. We waited nearly half an hour before anyone took our drinks order, one dish arrived lukewarm, and when we asked about it the response felt rushed. I understand restaurants get busy, but this made the evening feel less special than we had hoped.",
    reply: "Thank you for taking the time to explain this, Olivier. We are sorry the evening did not feel as special as it should have. Waiting that long for drinks and receiving a dish that was not served properly is not the standard we want to deliver. Your feedback has been shared with the team so we can look at both timing and how we respond when something needs attention during service.",
    loc: "Rotterdam Markthal", platform: "Google", status: "auto", date: "02/06/2026", time: "13:17",
    confidence: 0.78 },
  { id: "h12", name: "Priya N.", rating: 5, review: "This was our first dinner in Utrecht after moving nearby and it genuinely made us feel at home. The host noticed we were celebrating, the kitchen sent out each course with great timing, and the terrace had such a calm energy even though the restaurant was full. We especially loved that the staff explained the menu without making it feel rehearsed.",
    reply: "Thank you, Priya. What a wonderful first dinner to be part of. We are so happy the evening felt warm, calm, and personal, and that the team helped make your celebration feel at home in the neighbourhood. We will share your kind words with both the host team and the kitchen. We hope to welcome you back to the terrace soon.",
    loc: "Utrecht Domplein", platform: "Google", status: "auto", date: "01/06/2026", time: "18:42",
    confidence: 0.94 },
  { id: "h13", name: "Sven L.", rating: 5, review: "Lovely dinner with attentive service and excellent wine advice.",
    reply: "Thank you, Sven. We are so glad the dinner and wine advice landed well. We hope to welcome you back soon.",
    loc: "Amsterdam Centrum", platform: "Google", status: "auto", date: "31/05/2026", time: "20:06",
    confidence: 0.96 },
  { id: "h14", name: "Nina P.", rating: 4, review: "The terrace was beautiful and the staff were warm. Dessert took a little longer than expected but everything tasted great.",
    reply: "Thank you, Nina. We are happy you enjoyed the terrace, the team, and the food. We appreciate your note about dessert timing and will keep an eye on that rhythm.",
    loc: "Amsterdam Centrum", platform: "Google", status: "auto", date: "31/05/2026", time: "17:42",
    confidence: 0.89 },
  { id: "h15", name: "Koen D.", rating: 3, review: "Good flavors overall, but the room felt loud and the pacing was uneven.",
    reply: "Thank you for the honest feedback, Koen. We are glad the flavours worked for you and will take your comments on noise and pacing back to the team.",
    loc: "Rotterdam Markthal", platform: "Google", status: "unanswered", date: "30/05/2026", time: "21:34", isNew: true,
    confidence: 0.7 },
  { id: "h16", name: "Aisha R.", rating: 5, review: "A really polished evening. The host team made us feel looked after from the moment we arrived.",
    reply: "Thank you, Aisha. It is wonderful to hear the evening felt polished and welcoming from the start. We will share this with the host team.",
    loc: "Utrecht Domplein", platform: "Google", status: "auto", date: "30/05/2026", time: "19:19",
    confidence: 0.97 },
  { id: "h17", name: "Tom V.", rating: 5, review: "Fantastic lunch. The team balanced being friendly and professional perfectly.",
    reply: "Thank you, Tom. We are delighted lunch felt both relaxed and well looked after. We hope to see you again soon.",
    loc: "Amsterdam Centrum", platform: "Google", status: "auto", date: "29/05/2026", time: "13:28",
    confidence: 0.95 },
  { id: "h18", name: "Clara J.", rating: 2, review: "The food was nice, but our reservation was not found and we had to wait in the entrance for too long.",
    reply: "Thank you for telling us, Clara. We are sorry the reservation issue made the start of your visit feel uncomfortable. This has been shared with the team so we can improve the arrival experience.",
    loc: "Rotterdam Markthal", platform: "Yelp", status: "sent", date: "29/05/2026", time: "11:57",
    confidence: 0.76 },
  { id: "h19", name: "Ruben M.", rating: 4, review: "Great oysters and the wine pairing was clever. The music was slightly too loud near the bar.",
    reply: "Thank you, Ruben. We are glad you enjoyed the oysters and wine pairing, and we appreciate the note about the music near the bar.",
    loc: "Amsterdam Centrum", platform: "Google", status: "auto", date: "28/05/2026", time: "22:10",
    confidence: 0.9 },
  { id: "h20", name: "Hannah S.", rating: 5, review: "Everything felt effortless. Our server remembered small details and made the evening special.",
    reply: "Thank you, Hannah. We love hearing that the service felt personal and effortless. We hope to welcome you back for another special evening.",
    loc: "Utrecht Domplein", platform: "Google", status: "auto", date: "28/05/2026", time: "20:44",
    confidence: 0.98 },
  { id: "h21", name: "Bas T.", rating: 3, review: "Nice place and friendly staff, but the main course was not as memorable as expected.",
    reply: "Thank you for visiting, Bas. We are glad the team made you feel welcome and appreciate your feedback on the main course.",
    loc: "Amsterdam Centrum", platform: "Google", status: "failed", date: "27/05/2026", time: "18:03",
    confidence: 0.68 },
  { id: "h22", name: "Mila G.", rating: 5, review: "The brunch was excellent and the staff made our family table feel easy, even with two children.",
    reply: "Thank you, Mila. We are so pleased brunch felt easy and enjoyable for the whole family. We hope to welcome you back soon.",
    loc: "Rotterdam Markthal", platform: "Google", status: "auto", date: "27/05/2026", time: "12:16",
    confidence: 0.96 },
  { id: "h23", name: "Lotte F.", rating: 4, review: "Beautiful setting and a very kind server. We would have liked a bit more explanation of the specials.",
    reply: "Thank you, Lotte. We are happy you enjoyed the setting and service, and we will take your note about explaining the specials back to the team.",
    loc: "Utrecht Domplein", platform: "Tripadvisor", status: "auto", date: "26/05/2026", time: "19:52",
    confidence: 0.88 },
  { id: "h24", name: "Yara B.", rating: 1, review: "Our table was squeezed into a corner and the service felt inattentive throughout the meal.",
    reply: "Thank you for sharing this, Yara. We are sorry the table and service did not feel comfortable or attentive. Your feedback has been shared with the floor team.",
    loc: "Amsterdam Centrum", platform: "Google", status: "unanswered", date: "26/05/2026", time: "16:09", isNew: true,
    confidence: 0.57 },
  { id: "h25", name: "Victor H.", rating: 5, review: "Wonderful seafood, relaxed timing, and a team that clearly enjoys what they do.",
    reply: "Thank you, Victor. We are delighted the seafood, pacing, and team energy made the visit enjoyable. We hope to see you again soon.",
    loc: "Rotterdam Markthal", platform: "Google", status: "auto", date: "25/05/2026", time: "21:01",
    confidence: 0.97 },
  { id: "h26", name: "Eva C.", rating: 4, review: "The aperitif and starters were excellent. One wine was not quite to our taste, but the team handled it gracefully.",
    reply: "Thank you, Eva. We are glad the aperitif and starters stood out, and that the team handled the wine feedback with care.",
    loc: "Amsterdam Centrum", platform: "Google", status: "auto", date: "25/05/2026", time: "18:37",
    confidence: 0.91 },
  { id: "h27", name: "Samir A.", rating: 5, review: "One of the best service experiences we have had in a long time.",
    reply: "Thank you, Samir. That is wonderful to read, and we will share your words with the full service team.",
    loc: "Utrecht Domplein", platform: "Google", status: "auto", date: "24/05/2026", time: "20:22",
    confidence: 0.98 },
  { id: "h28", name: "Iris N.", rating: 3, review: "The concept is strong, but some dishes felt too salty and the pace slowed down near the end.",
    reply: "Thank you for the thoughtful feedback, Iris. We appreciate your notes on seasoning and pacing and will share them with the kitchen and service team.",
    loc: "Rotterdam Markthal", platform: "Yelp", status: "sent", date: "24/05/2026", time: "14:45",
    confidence: 0.73 },
  { id: "h29", name: "Jeroen W.", rating: 5, review: "We came for a birthday dinner and the team made it feel quietly special without overdoing it.",
    reply: "Thank you, Jeroen. We are so glad the birthday dinner felt special in the right way. We hope to welcome you back soon.",
    loc: "Amsterdam Centrum", platform: "Google", status: "auto", date: "23/05/2026", time: "21:33",
    confidence: 0.96 },
  { id: "h30", name: "Olivia K.", rating: 4, review: "Lovely cocktails and a warm room. The table felt a little cramped once all the dishes arrived.",
    reply: "Thank you, Olivia. We are happy you enjoyed the cocktails and atmosphere, and we appreciate the note about table space during service.",
    loc: "Utrecht Domplein", platform: "Google", status: "auto", date: "23/05/2026", time: "17:24",
    confidence: 0.87 },
  { id: "h31", name: "Max B.", rating: 2, review: "The service was friendly, but we waited too long between courses and left a bit disappointed.",
    reply: "Thank you, Max. We are sorry the pacing left you disappointed, even though the team was friendly. We will take this back into service planning.",
    loc: "Rotterdam Markthal", platform: "Google", status: "failed", date: "22/05/2026", time: "20:08",
    confidence: 0.69 },
  { id: "h32", name: "Sophie E.", rating: 5, review: "Perfect spot for a long dinner with friends. The staff made the evening feel easy and generous.",
    reply: "Thank you, Sophie. We are delighted your dinner with friends felt easy, generous, and well looked after. We hope to welcome you back soon.",
    loc: "Amsterdam Centrum", platform: "Tripadvisor", status: "auto", date: "22/05/2026", time: "13:31",
    confidence: 0.95 },
];

const STATUS_META = {
  unanswered: { label: "Outstanding",    tone: "neutral" },
  sent:       { label: "Replied",        tone: "info" },
  auto:       { label: "Replied by agent", tone: "ai" },
  failed:     { label: "Failed",         tone: "error" },
};

const HISTORY_FILTERS = [
  { key: "all", label: "All" },
  { key: "unanswered", label: "Outstanding" },
  { key: "sent", label: "Replied" },
  { key: "auto", label: "Replied by agent" },
  { key: "failed", label: "Failed" },
];

const TONES = [
  { key: "pro", title: "Professional", desc: "Polished, courteous, on-brand." },
  { key: "warm", title: "Warm & friendly", desc: "Personable and welcoming." },
  { key: "casual", title: "Casual", desc: "Relaxed, conversational tone." },
  { key: "formal", title: "Formal", desc: "Reserved and precise." },
];

const ONBOARDING = [
  { key: "when", kicker: "Step 1 of 5", title: "Choose when the agent replies",
    p: "Decide which reviews are safe to send automatically and which should wait for you." },
  { key: "tone", kicker: "Step 2 of 5", title: "Pick the tone of voice",
    p: "Every reply is written in this voice. You can fine-tune it any time." },
  { key: "rules", kicker: "Step 3 of 5", title: "Add house rules",
    p: "Custom instructions the agent follows on every reply." },
  { key: "locations", kicker: "Step 4 of 5", title: "Connect your locations",
    p: "Choose which locations the agent manages reviews for." },
  { key: "done", kicker: "Step 5 of 5", title: "Your review agent is ready",
    p: "SOUS will now check new reviews, reply to safe ones, and bring sensitive replies to you for approval." },
];

Object.assign(window, {
  RRA_DATA: { LOCATIONS, STATS, ATTENTION, ACTIVITY, HISTORY, STATUS_META, HISTORY_FILTERS, TONES, ONBOARDING },
});
